Feature engineering: <br>Using domain and data knowledge to create novel features as inputs for ML models, Often more art than science
<br><br>
Some rules of thumb <br>
•Use intuition: “What information would a human use to predict?”
<br>•Try generating many features, then apply dimensionality reduction if needed<br>•Consider transformations of attributes (e.g., squaring)<br>•Consider combinations of attributes (e.g., multiplication)<br>•Do not overthink or include too much manual logic (balance with the 1st rule about intuition...)<br><br>•scikit-learn:sklearn.feature_extraction

========================================================<br>

1. Scaling

In [22]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler
std_scaler = StandardScaler()
mm_scaler = MinMaxScaler()
import numpy as np
data = np.array([[2,3,4], [3,4,5]])
scaled_data_std = std_scaler.fit_transform(data)
scaled_data_mm = mm_scaler.fit_transform(data)

print(data, "\n\n", scaled_data_std, "\n\n",scaled_data_mm)

[[2 3 4]
 [3 4 5]] 

 [[-1. -1. -1.]
 [ 1.  1.  1.]] 

 [[0. 0. 0.]
 [1. 1. 1.]]


C:\Users\joshuang\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int32 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\Users\joshuang\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int32 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
C:\Users\joshuang\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int32 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


======================================<br>

2. Polynomial Transformation <br>
- degree made too high leads to overfitting



In [27]:
from sklearn.preprocessing import PolynomialFeatures
quadratic = PolynomialFeatures(degree = 2)
data = np.array([[1],[2]])
X_quad = quadratic.fit_transform(data)
print(data, "\n\n", X_quad)

[[1]
 [2]] 

 [[1. 1. 1.]
 [1. 2. 4.]]
